services:
  - type: web
    name: kwik-tips-backend
    runtime: docker
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/kwiktips-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
